function main()
%MAIN Run the complete FSO satellite-network analysis.
%
% This project reproduces:
%   1. Required LISL transmit power versus link distance.
%   2. Uplink/downlink outage probability versus average SNR.
%
% Generated figures are saved in figures/.
% Generated result tables are saved in results/.

close all;
clc;

fprintf('============================================\n');
fprintf(' FSO Satellite Network Analysis\n');
fprintf('============================================\n\n');

%% Locate the project folders

% Find the folder containing this main.m file.
mainFile = mfilename('fullpath');
projectFolder = fileparts(mainFile);

modelsFolder = fullfile(projectFolder, 'models');
simulationsFolder = fullfile(projectFolder, 'simulations');
figuresFolder = fullfile(projectFolder, 'figures');
resultsFolder = fullfile(projectFolder, 'results');

%% Confirm that the required folders exist

if ~isfolder(modelsFolder)
    error('The models folder could not be found.');
end

if ~isfolder(simulationsFolder)
    error('The simulations folder could not be found.');
end

% Create output folders if they do not already exist.
if ~isfolder(figuresFolder)
    mkdir(figuresFolder);
end

if ~isfolder(resultsFolder)
    mkdir(resultsFolder);
end

%% Add project functions to the MATLAB search path

addpath(projectFolder);
addpath(modelsFolder);
addpath(simulationsFolder);

%% Simulation 1: Required power versus LISL distance

fprintf('Running required-power simulation...\n');

run(fullfile(simulationsFolder, 'powerVsDistance.m'));

% Save the figure generated by powerVsDistance.m.
powerFigure = gcf;

exportgraphics( ...
    powerFigure, ...
    fullfile(figuresFolder, 'power_vs_distance.png'), ...
    'Resolution', 300);

% resultsTable is produced by powerVsDistance.m.
writetable( ...
    resultsTable, ...
    fullfile(resultsFolder, 'power_vs_distance.csv'));

fprintf('Power-versus-distance simulation completed.\n\n');

%% Simulation 2: Outage probability versus average SNR

fprintf('Running outage-probability simulation...\n');

run(fullfile(simulationsFolder, 'outageVsSNR.m'));

% outageVsSNR.m already saves its generated figure.
% resultsAt30dB is produced by outageVsSNR.m.
writetable( ...
    resultsAt30dB, ...
    fullfile(resultsFolder, 'outage_at_30dB.csv'));

fprintf('Outage-probability simulation completed.\n\n');

%% Completion message

fprintf('============================================\n');
fprintf(' Analysis completed successfully.\n');
fprintf(' Figures: %s\n', figuresFolder);
fprintf(' Results: %s\n', resultsFolder);
fprintf('============================================\n');

end